name = "KernelForge"
uuid = "d2e71dfc-f0f5-4b9d-8de2-a66a4c724860"
version = "0.1.3"
authors = ["Emmanuel Pilliat <epilliat@gmail.com>"]

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
KernelIntrinsics = "f9588fbb-d238-4998-b15a-468e8766d49a"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
KernelForgeAMDGPUExt = "AMDGPU"
KernelForgeCUDAExt = "CUDA"

[compat]
CUDA = "5"
AMDGPU = "1"
ArgCheck = "2.5.0"
Atomix = "1.1.2"
KernelAbstractions = "0.9.39"
KernelIntrinsics = "0.1.5"
julia = "1.10"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "Test"]
