# --- BEGIN MapReduce1D ---
# Generated by data/tuning/mapreduce1d/autotune.jl on 2026-07-02
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^27/2^28/2^30
@inline function KernelForge.default_workgroup(
    ::KernelForge.A100, ::Type{KernelForge.MapReduce1D}, n, ::Type{T}) where T
    n < 1048576 ? 256 :
        n < 2097152 ? 256 :
        n < 8388608 ? 1024 :
        n < 189812531 ? 512 :
        256
end

@inline function KernelForge.default_blocks(
    ::KernelForge.A100, ::Type{KernelForge.MapReduce1D}, n, ::Type{T}) where T
    n < 1048576 ? 3456 :
        n < 2097152 ? 3456 :
        n < 8388608 ? 432 :
        n < 189812531 ? 216 :
        864
end

@inline function KernelForge.default_nitem(
    ::KernelForge.A100, ::Type{KernelForge.MapReduce1D}, n::Int, ::Type{T}) where T
    nb = n * sizeof(T)
    nitem_f32 = nb < 4194304 ? 4 :
        nb < 8388608 ? 4 :
        nb < 33554432 ? 8 :
        nb < 134217728 ? 1 :
        nb < 759250124 ? 16 :
        8
    return clamp(nitem_f32 * 4 ÷ sizeof(T), 1, 32)
end

# --- END MapReduce1D ---


# --- BEGIN MapReduce1D_Float64 ---
# Generated by data/tuning/mapreduce1d/autotune.jl on 2026-07-03 (type-specific: Float64)
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^27/2^28/2^30
@inline function KernelForge.default_workgroup(
    ::KernelForge.A100, ::Type{KernelForge.MapReduce1D}, n, ::Type{Float64})
    n < 1048576 ? 256 :
        n < 2097152 ? 256 :
        n < 8388608 ? 1024 :
        n < 33554432 ? 256 :
        1024
end

@inline function KernelForge.default_blocks(
    ::KernelForge.A100, ::Type{KernelForge.MapReduce1D}, n, ::Type{Float64})
    n < 1048576 ? 1728 :
        n < 2097152 ? 1728 :
        n < 8388608 ? 108 :
        n < 33554432 ? 216 :
        n < 536870912 ? 1728 :
        108
end

@inline function KernelForge.default_nitem(
    ::KernelForge.A100, ::Type{KernelForge.MapReduce1D}, n::Int, ::Type{Float64})
    n < 1048576 ? 4 :
        n < 2097152 ? 4 :
        n < 536870912 ? 1 :
        8
end

# --- END MapReduce1D_Float64 ---


# --- BEGIN MapReduce1D_UInt8 ---
# Generated by data/tuning/mapreduce1d/autotune.jl on 2026-07-03 (type-specific: UInt8)
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^27/2^28/2^30
@inline function KernelForge.default_workgroup(
    ::KernelForge.A100, ::Type{KernelForge.MapReduce1D}, n, ::Type{UInt8})
    n < 1048576 ? 512 :
        n < 8388608 ? 512 :
        n < 94906265 ? 256 :
        n < 189812531 ? 512 :
        n < 536870912 ? 256 :
        1024
end

@inline function KernelForge.default_blocks(
    ::KernelForge.A100, ::Type{KernelForge.MapReduce1D}, n, ::Type{UInt8})
    n < 1048576 ? 13824 :
        n < 2097152 ? 13824 :
        n < 33554432 ? 864 :
        n < 94906265 ? 432 :
        n < 189812531 ? 216 :
        n < 536870912 ? 432 :
        216
end

@inline function KernelForge.default_nitem(
    ::KernelForge.A100, ::Type{KernelForge.MapReduce1D}, n::Int, ::Type{UInt8})
    n < 1048576 ? 1 :
        n < 2097152 ? 1 :
        n < 8388608 ? 16 :
        n < 33554432 ? 8 :
        16
end

# --- END MapReduce1D_UInt8 ---



# --- BEGIN SortColumns ---
# Generated by data/tuning/sort_columns/autotune.jl on 2026-07-03
# Cross-over thresholds between oem_sort_columns! (K ≤ thr) and
# batched_radix_sort_columns! (K > thr), per eltype.
@inline KernelForge.default_sort_columns_threshold(::KernelForge.A100, ::Type{UInt8}) = 256
@inline KernelForge.default_sort_columns_threshold(::KernelForge.A100, ::Type{Int8}) = 256
@inline KernelForge.default_sort_columns_threshold(::KernelForge.A100, ::Type{Bool}) = 256
@inline KernelForge.default_sort_columns_threshold(::KernelForge.A100, ::Type{UInt16}) = 512
@inline KernelForge.default_sort_columns_threshold(::KernelForge.A100, ::Type{Int16}) = 512
@inline KernelForge.default_sort_columns_threshold(::KernelForge.A100, ::Type{UInt32}) = 1024
@inline KernelForge.default_sort_columns_threshold(::KernelForge.A100, ::Type{Int32}) = 1024
@inline KernelForge.default_sort_columns_threshold(::KernelForge.A100, ::Type{Float32}) = 1024
@inline KernelForge.default_sort_columns_threshold(::KernelForge.A100, ::Type{UInt64}) = 4096
@inline KernelForge.default_sort_columns_threshold(::KernelForge.A100, ::Type{Int64}) = 4096
@inline KernelForge.default_sort_columns_threshold(::KernelForge.A100, ::Type{Float64}) = 4096
# --- END SortColumns ---

















# --- BEGIN Scan1D ---
# Generated by data/tuning/scan/autotune.jl on 2026-07-07
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^28/2^30
@inline function KernelForge.default_workgroup(
    ::KernelForge.A100, ::Type{KernelForge.Scan1D}, n, ::Type{T}) where T
    n < 1048576 ? 256 :
        n < 2097152 ? 256 :
        n < 536870912 ? 512 :
        1024
end

@inline function KernelForge.default_nitem(
    ::KernelForge.A100, ::Type{KernelForge.Scan1D}, n::Int, ::Type{T}) where T
    nb = n * sizeof(T)
    nitem_f32 = nb < 4194304 ? 8 :
        nb < 2147483648 ? 8 :
        16
    return clamp(nitem_f32 * 4 ÷ sizeof(T), 1, 32)
end

# --- END Scan1D ---

# --- BEGIN Scan1D_Float64 ---
# Generated by data/tuning/scan/autotune.jl on 2026-07-07 (type-specific: Float64)
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^28/2^30
@inline function KernelForge.default_workgroup(
    ::KernelForge.A100, ::Type{KernelForge.Scan1D}, n, ::Type{Float64})
    n < 1048576 ? 256 :
        n < 2097152 ? 256 :
        n < 8388608 ? 128 :
        n < 536870912 ? 256 :
        256
end

@inline function KernelForge.default_nitem(
    ::KernelForge.A100, ::Type{KernelForge.Scan1D}, n::Int, ::Type{Float64})
    n < 1048576 ? 20 :
        n < 2097152 ? 20 :
        n < 8388608 ? 28 :
        n < 536870912 ? 20 :
        20
end

@inline function KernelForge.default_scan_family(
    ::KernelForge.A100, ::Type{KernelForge.Scan1D}, n, ::Type{Float64})
    n < 1048576 ? :transposed :
        n < 2097152 ? :transposed :
        n < 8388608 ? :transposed :
        n < 536870912 ? :transposed :
        :blocked
end

# --- END Scan1D_Float64 ---

# --- BEGIN Scan1D_UInt8 ---
# Generated by data/tuning/scan/autotune.jl on 2026-07-07 (type-specific: UInt8)
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^28/2^30
@inline function KernelForge.default_workgroup(
    ::KernelForge.A100, ::Type{KernelForge.Scan1D}, n, ::Type{UInt8})
    n < 1048576 ? 128 :
        128
end

@inline function KernelForge.default_nitem(
    ::KernelForge.A100, ::Type{KernelForge.Scan1D}, n::Int, ::Type{UInt8})
    n < 1048576 ? 32 :
        32
end

# --- END Scan1D_UInt8 ---
