# --- BEGIN Scan1D ---
# Generated by data/tuning/scan/autotune.jl on 2026-07-09
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^28/2^30
@inline function KernelForge.default_workgroup(
    ::KernelForge.MI300A, ::Type{KernelForge.Scan1D}, n, ::Type{T}) where T
    n < 1048576 ? 1024 :
        n < 2097152 ? 1024 :
        n < 8388608 ? 256 :
        512
end

@inline function KernelForge.default_nitem(
    ::KernelForge.MI300A, ::Type{KernelForge.Scan1D}, n::Int, ::Type{T}) where T
    nb = n * sizeof(T)
    nitem_f32 = nb < 4194304 ? 16 :
        nb < 8388608 ? 16 :
        32
    return clamp(nitem_f32 * 4 ÷ sizeof(T), 1, 32)
end

# --- END Scan1D ---

# --- BEGIN Scan1D_Float64 ---
# Generated by data/tuning/scan/autotune.jl on 2026-07-09 (type-specific: Float64)
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^28/2^30
# 2026-07-10: large-N Nitem 32→16 after the AMD split-path descriptor BYPASS landed
# (scan_desc_bypass — coherent relaxed-atomic lookback, no acquire; see scan.jl). Cheaper
# lookback shifts the F64 optimum DOWN to Ni16 (higher copy ceiling): re-measured on MI300A
# 1e9 — Ni16 35.8% vs Ni32 34.1% vs Ni8 26.1% (was 24% pre-bypass). Small-N cells unchanged
# (lookback-light there). Hand-edited from a targeted sweep (xp/scan_parity/retune_f64.jl);
# a full autotune re-run would rediscover the same.
#
# 2026-07-13: F64 on MI300A now takes the PACKED-128 path (scan_use_packed128 — CDNA3 + 8-byte
# primitive; single coherent+atomic dwordx4 descriptor, one lookback round-trip instead of
# flag→value). Re-swept on that kernel at 1e9: Ni16/wg512 = 40.2% peak / 1.195× rocPRIM, beating
# Ni16/wg1024 (37.8%) and Ni32/wg512 (37.2%); Ni8 still collapses (25–29% — 4× the tiles ⇒ 4× the
# lookback chain, which the cheaper descriptor does not offset). So large-N workgroup 1024 → 512.
# Small-N cells left alone (lookback-light; packed-128 already improves them: 1e7 124→111 µs).
@inline function KernelForge.default_workgroup(
    ::KernelForge.MI300A, ::Type{KernelForge.Scan1D}, n, ::Type{Float64})
    n < 1048576 ? 1024 :
        n < 2097152 ? 1024 :
        512
end

@inline function KernelForge.default_nitem(
    ::KernelForge.MI300A, ::Type{KernelForge.Scan1D}, n::Int, ::Type{Float64})
    n < 1048576 ? 8 :
        n < 2097152 ? 8 :
        16
end

# --- END Scan1D_Float64 ---

# --- BEGIN Scan1D_UInt8 ---
# Generated by data/tuning/scan/autotune.jl on 2026-07-09 (type-specific: UInt8)
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^28/2^30
@inline function KernelForge.default_workgroup(
    ::KernelForge.MI300A, ::Type{KernelForge.Scan1D}, n, ::Type{UInt8})
    n < 1048576 ? 1024 :
        n < 2097152 ? 1024 :
        n < 33554432 ? 1024 :
        n < 134217728 ? 512 :
        1024
end

@inline function KernelForge.default_nitem(
    ::KernelForge.MI300A, ::Type{KernelForge.Scan1D}, n::Int, ::Type{UInt8})
    n < 1048576 ? 8 :
        n < 2097152 ? 8 :
        n < 33554432 ? 32 :
        n < 134217728 ? 32 :
        32
end

# --- END Scan1D_UInt8 ---
