# --- BEGIN Scan1D ---
# Generated by data/tuning/scan/autotune.jl on 2026-06-11 (re-tuned post packed
# descriptor, with WG_WAVES extended to 2/4 so 128/256-thread tiles were swept).
# Result: big wg=1024 tiles still win — smaller ~16 KB rocPRIM-style tiles do NOT
# help KF's scan; only the mid-N F32 Ni=16→32 boundary shifted (nb 8.4M→33.5M).
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^28/2^30
@inline function KernelForge.default_workgroup(
    ::KernelForge.MI300X, ::Type{KernelForge.Scan1D}, n, ::Type{T}) where T
    n < 1048576 ? 512 :
        n < 2097152 ? 512 :
        1024
end

@inline function KernelForge.default_nitem(
    ::KernelForge.MI300X, ::Type{KernelForge.Scan1D}, n::Int, ::Type{T}) where T
    nb = n * sizeof(T)
    nitem_f32 = nb < 4194304 ? 16 :
        nb < 33554432 ? 16 :
        32
    return clamp(nitem_f32 * 4 ÷ sizeof(T), 1, 32)
end

# --- END Scan1D ---

# --- BEGIN Scan1D_Float64 ---
# Generated by data/tuning/scan/autotune.jl on 2026-06-10 (type-specific: Float64)
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^28/2^30
@inline function KernelForge.default_workgroup(
    ::KernelForge.MI300X, ::Type{KernelForge.Scan1D}, n, ::Type{Float64})
    n < 1048576 ? 1024 :
        1024
end

@inline function KernelForge.default_nitem(
    ::KernelForge.MI300X, ::Type{KernelForge.Scan1D}, n::Int, ::Type{Float64})
    n < 1048576 ? 8 :
        n < 2097152 ? 8 :
        16
end

# --- END Scan1D_Float64 ---

# --- BEGIN MapReduce1D ---
# Generated by data/tuning/mapreduce1d/autotune.jl on 2026-06-10
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^27/2^28/2^30
@inline function KernelForge.default_workgroup(
    ::KernelForge.MI300X, ::Type{KernelForge.MapReduce1D}, n, ::Type{T}) where T
    n < 1048576 ? 512 :
        n < 2097152 ? 512 :
        n < 8388608 ? 256 :
        n < 33554432 ? 512 :
        n < 94906265 ? 256 :
        n < 189812531 ? 1024 :
        512
end

@inline function KernelForge.default_blocks(
    ::KernelForge.MI300X, ::Type{KernelForge.MapReduce1D}, n, ::Type{T}) where T
    n < 1048576 ? 608 :
        n < 2097152 ? 608 :
        n < 8388608 ? 256 :
        n < 33554432 ? 608 :
        n < 94906265 ? 256 :
        304
end

@inline function KernelForge.default_nitem(
    ::KernelForge.MI300X, ::Type{KernelForge.MapReduce1D}, n::Int, ::Type{T}) where T
    nb = n * sizeof(T)
    nitem_f32 = nb < 4194304 ? 2 :
        nb < 8388608 ? 2 :
        nb < 33554432 ? 16 :
        nb < 134217728 ? 8 :
        nb < 379625060 ? 16 :
        nb < 2147483648 ? 8 :
        16
    return clamp(nitem_f32 * 4 ÷ sizeof(T), 1, 32)
end

# --- END MapReduce1D ---

# --- BEGIN MapReduce1D_Float64 ---
# Generated by data/tuning/mapreduce1d/autotune.jl on 2026-06-10 (type-specific: Float64)
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^27/2^28/2^30
@inline function KernelForge.default_workgroup(
    ::KernelForge.MI300X, ::Type{KernelForge.MapReduce1D}, n, ::Type{Float64})
    n < 1048576 ? 1024 :
        n < 8388608 ? 1024 :
        n < 33554432 ? 256 :
        n < 189812531 ? 512 :
        n < 536870912 ? 1024 :
        512
end

@inline function KernelForge.default_blocks(
    ::KernelForge.MI300X, ::Type{KernelForge.MapReduce1D}, n, ::Type{Float64})
    n < 1048576 ? 304 :
        n < 8388608 ? 304 :
        n < 33554432 ? 256 :
        304
end

@inline function KernelForge.default_nitem(
    ::KernelForge.MI300X, ::Type{KernelForge.MapReduce1D}, n::Int, ::Type{Float64})
    n < 1048576 ? 4 :
        n < 2097152 ? 4 :
        n < 8388608 ? 2 :
        n < 33554432 ? 8 :
        n < 536870912 ? 4 :
        8
end

# --- END MapReduce1D_Float64 ---

# --- BEGIN MapReduce1D_UInt8 ---
# Generated by data/tuning/mapreduce1d/autotune.jl on 2026-06-10 (type-specific: UInt8)
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^27/2^28/2^30
@inline function KernelForge.default_workgroup(
    ::KernelForge.MI300X, ::Type{KernelForge.MapReduce1D}, n, ::Type{UInt8})
    n < 1048576 ? 1024 :
        n < 2097152 ? 1024 :
        n < 33554432 ? 512 :
        n < 536870912 ? 1024 :
        512
end

@inline function KernelForge.default_blocks(
    ::KernelForge.MI300X, ::Type{KernelForge.MapReduce1D}, n, ::Type{UInt8})
    n < 1048576 ? 304 :
        304
end

@inline function KernelForge.default_nitem(
    ::KernelForge.MI300X, ::Type{KernelForge.MapReduce1D}, n::Int, ::Type{UInt8})
    n < 1048576 ? 1 :
        n < 8388608 ? 1 :
        n < 33554432 ? 2 :
        n < 94906265 ? 4 :
        n < 536870912 ? 8 :
        32
end

# --- END MapReduce1D_UInt8 ---
