











# --- BEGIN MapReduce1D ---
# Generated by data/tuning/mapreduce1d/autotune.jl on 2026-05-28
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^28/2^30
@inline function KernelForge.default_workgroup(
    ::KernelForge.RTX1000, ::Type{KernelForge.MapReduce1D}, n, ::Type{T}) where T
    n < 1048576 ? 256 :
        n < 33554432 ? 256 :
        n < 134217728 ? 1024 :
        n < 536870912 ? 512 :
        1024
end

@inline function KernelForge.default_blocks(
    ::KernelForge.RTX1000, ::Type{KernelForge.MapReduce1D}, n, ::Type{T}) where T
    n < 1048576 ? 40 :
        n < 2097152 ? 40 :
        n < 8388608 ? 160 :
        n < 33554432 ? 80 :
        n < 134217728 ? 20 :
        n < 536870912 ? 60 :
        20
end

@inline function KernelForge.default_nitem(
    ::KernelForge.RTX1000, ::Type{KernelForge.MapReduce1D}, n::Int, ::Type{T}) where T
    nb = n * sizeof(T)
    nitem_f32 = nb < 4194304 ? 1 :
        nb < 8388608 ? 1 :
        nb < 33554432 ? 16 :
        nb < 2147483648 ? 1 :
        4
    return clamp(nitem_f32 * 4 ÷ sizeof(T), 1, 16)
end

# --- END MapReduce1D ---


# --- BEGIN MapReduce1D_Int32 ---
# Generated by data/tuning/mapreduce1d/autotune.jl on 2026-05-28 (type-specific: Int32)
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^28/2^30
@inline function KernelForge.default_workgroup(
    ::KernelForge.RTX1000, ::Type{KernelForge.MapReduce1D}, n, ::Type{Int32})
    n < 1048576 ? 256 :
        n < 2097152 ? 256 :
        n < 8388608 ? 512 :
        n < 134217728 ? 256 :
        n < 536870912 ? 1024 :
        512
end

@inline function KernelForge.default_blocks(
    ::KernelForge.RTX1000, ::Type{KernelForge.MapReduce1D}, n, ::Type{Int32})
    n < 1048576 ? 20 :
        n < 2097152 ? 20 :
        n < 8388608 ? 80 :
        n < 33554432 ? 60 :
        n < 134217728 ? 120 :
        n < 536870912 ? 20 :
        60
end

@inline function KernelForge.default_nitem(
    ::KernelForge.RTX1000, ::Type{KernelForge.MapReduce1D}, n::Int, ::Type{Int32})
    n < 1048576 ? 16 :
        n < 8388608 ? 16 :
        1
end

# --- END MapReduce1D_Int32 ---

# --- BEGIN Scan1D ---
# Generated by data/tuning/scan/autotune.jl on 2026-05-28
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^28
@inline function KernelForge.default_workgroup(
    ::KernelForge.RTX1000, ::Type{KernelForge.Scan1D}, n, ::Type{T}) where T
    n < 1048576 ? 256 :
        n < 8388608 ? 256 :
        n < 33554432 ? 512 :
        n < 134217728 ? 256 :
        512
end

@inline function KernelForge.default_nitem(
    ::KernelForge.RTX1000, ::Type{KernelForge.Scan1D}, n::Int, ::Type{T}) where T
    nb = n * sizeof(T)
    nitem_f32 = nb < 4194304 ? 8 :
        nb < 8388608 ? 8 :
        nb < 33554432 ? 16 :
        nb < 134217728 ? 4 :
        nb < 536870912 ? 16 :
        4
    return clamp(nitem_f32 * 4 ÷ sizeof(T), 1, 16)
end

# --- END Scan1D ---

# --- BEGIN Sort1D_size4 ---
# Generated by xp/sort/autotune/autotune.jl on 2026-05-29  (sizeof(T)=4, onesweep path)
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^28
@inline function KernelForge.default_workgroup(
    ::KernelForge.RTX1000, ::Type{KernelForge.Sort1D}, n, ::Type{T}) where T<:Union{UInt32, Int32, Float32}
    n < 1048576 ? 256 :
        256
end

@inline function KernelForge.default_nitem(
    ::KernelForge.RTX1000, ::Type{KernelForge.Sort1D}, n, ::Type{T}) where T<:Union{UInt32, Int32, Float32}
    n < 1048576 ? 8 :
        n < 8388608 ? 8 :
        n < 33554432 ? 4 :
        n < 134217728 ? 16 :
        8
end

@inline function KernelForge.default_nchunks(
    ::KernelForge.RTX1000, ::Type{KernelForge.Sort1D}, n, ::Type{T}) where T<:Union{UInt32, Int32, Float32}
    n < 1048576 ? 4 :
        n < 33554432 ? 4 :
        n < 134217728 ? 2 :
        4
end

# --- END Sort1D_size4 ---


# --- BEGIN Sort1D_byte ---
# Generated by xp/sort/autotune/autotune.jl on 2026-05-29  (sizeof(T)=1, byte_sort path)
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^28
@inline function KernelForge.default_workgroup(
    ::KernelForge.RTX1000, ::Type{KernelForge.Sort1D}, n, ::Type{T}) where T<:Union{UInt8, Int8, Bool}
    n < 1048576 ? 256 :
        256
end

@inline function KernelForge.default_nitem(
    ::KernelForge.RTX1000, ::Type{KernelForge.Sort1D}, n, ::Type{T}) where T<:Union{UInt8, Int8, Bool}
    n < 1048576 ? 8 :
        8
end

@inline function KernelForge.default_nchunks(
    ::KernelForge.RTX1000, ::Type{KernelForge.Sort1D}, n, ::Type{T}) where T<:Union{UInt8, Int8, Bool}
    n < 1048576 ? 1 :
        1
end

# --- END Sort1D_byte ---


# --- BEGIN MapReduce1D_UInt8 ---
# Generated by data/tuning/mapreduce1d/autotune.jl on 2026-05-31 (type-specific: UInt8)
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^27/2^28/2^30
@inline function KernelForge.default_workgroup(
    ::KernelForge.RTX1000, ::Type{KernelForge.MapReduce1D}, n, ::Type{UInt8})
    n < 1048576 ? 512 :
        n < 94906265 ? 512 :
        n < 536870912 ? 256 :
        1024
end

@inline function KernelForge.default_blocks(
    ::KernelForge.RTX1000, ::Type{KernelForge.MapReduce1D}, n, ::Type{UInt8})
    n < 1048576 ? 40 :
        n < 33554432 ? 40 :
        n < 94906265 ? 2560 :
        n < 189812531 ? 4000 :
        80
end

@inline function KernelForge.default_nitem(
    ::KernelForge.RTX1000, ::Type{KernelForge.MapReduce1D}, n::Int, ::Type{UInt8})
    n < 1048576 ? 2 :
        n < 2097152 ? 2 :
        n < 8388608 ? 16 :
        n < 33554432 ? 8 :
        16
end

# --- END MapReduce1D_UInt8 ---

# --- BEGIN Scan1D_Float64 ---
# Generated by data/tuning/scan/autotune.jl on 2026-06-02 (type-specific: Float64)
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^28
@inline function KernelForge.default_workgroup(
    ::KernelForge.RTX1000, ::Type{KernelForge.Scan1D}, n, ::Type{Float64})
    n < 1048576 ? 256 :
        n < 8388608 ? 256 :
        n < 33554432 ? 1024 :
        n < 134217728 ? 256 :
        1024
end

@inline function KernelForge.default_nitem(
    ::KernelForge.RTX1000, ::Type{KernelForge.Scan1D}, n::Int, ::Type{Float64})
    n < 1048576 ? 8 :
        n < 2097152 ? 8 :
        n < 8388608 ? 4 :
        n < 33554432 ? 8 :
        n < 134217728 ? 4 :
        8
end

# --- END Scan1D_Float64 ---

# --- BEGIN MapReduce1D_Float64 ---
# Generated by data/tuning/mapreduce1d/autotune.jl on 2026-06-02 (type-specific: Float64)
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^27/2^28
@inline function KernelForge.default_workgroup(
    ::KernelForge.RTX1000, ::Type{KernelForge.MapReduce1D}, n, ::Type{Float64})
    n < 1048576 ? 256 :
        n < 2097152 ? 256 :
        n < 8388608 ? 1024 :
        n < 33554432 ? 512 :
        n < 189812531 ? 256 :
        1024
end

@inline function KernelForge.default_blocks(
    ::KernelForge.RTX1000, ::Type{KernelForge.MapReduce1D}, n, ::Type{Float64})
    n < 1048576 ? 20 :
        n < 8388608 ? 20 :
        n < 33554432 ? 1280 :
        n < 189812531 ? 80 :
        160
end

@inline function KernelForge.default_nitem(
    ::KernelForge.RTX1000, ::Type{KernelForge.MapReduce1D}, n::Int, ::Type{Float64})
    n < 1048576 ? 1 :
        n < 8388608 ? 1 :
        n < 33554432 ? 8 :
        1
end

# --- END MapReduce1D_Float64 ---

# --- BEGIN Scan1D_UInt8 ---
# Generated by data/tuning/scan/autotune.jl on 2026-06-02 (type-specific: UInt8)
# Per-N tuned at N=2^20/2^22/2^24/2^26/2^28
@inline function KernelForge.default_workgroup(
    ::KernelForge.RTX1000, ::Type{KernelForge.Scan1D}, n, ::Type{UInt8})
    n < 1048576 ? 512 :
        n < 8388608 ? 512 :
        n < 33554432 ? 256 :
        1024
end

@inline function KernelForge.default_nitem(
    ::KernelForge.RTX1000, ::Type{KernelForge.Scan1D}, n::Int, ::Type{UInt8})
    n < 1048576 ? 16 :
        16
end

# --- END Scan1D_UInt8 ---

# --- BEGIN Sort1D_size8 ---
# Generated by xp/sort/autotune/autotune.jl on 2026-06-03  (sizeof(T)=8, onesweep path)
# Per-N tuned at N=2^20/2^22/2^24/2^26
@inline function KernelForge.default_workgroup(
    ::KernelForge.RTX1000, ::Type{KernelForge.Sort1D}, n, ::Type{T}) where T<:Union{UInt64, Int64, Float64}
    n < 1048576 ? 256 :
        256
end

@inline function KernelForge.default_nitem(
    ::KernelForge.RTX1000, ::Type{KernelForge.Sort1D}, n, ::Type{T}) where T<:Union{UInt64, Int64, Float64}
    n < 1048576 ? 4 :
        n < 8388608 ? 4 :
        8
end

@inline function KernelForge.default_nchunks(
    ::KernelForge.RTX1000, ::Type{KernelForge.Sort1D}, n, ::Type{T}) where T<:Union{UInt64, Int64, Float64}
    n < 1048576 ? 4 :
        n < 8388608 ? 4 :
        2
end

# --- END Sort1D_size8 ---
